//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TABLAS
    {
        public int T_IDCAMPO { get; set; }
        public Nullable<int> T_IDTIPOTABLA { get; set; }
        public string T_NOMBRE { get; set; }
        public Nullable<int> T_VER { get; set; }
        public Nullable<int> T_VALOR { get; set; }
    }
}
